[package]
name = "dv"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
crossterm = "0.29.0"
memchr = "2.8.3"
ratatui = "0.30.2"
thiserror = "2.0.21"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[dev-dependencies]
criterion = "0.8.2"
dhat = "0.3.3"
proptest = "1.11.0"
saphyr = "0.1.0"
serde_json = "1.0.151"
tempfile = "3.27.0"

[[example]]
name = "gen"
test = true

[[bench]]
name = "load"
harness = false
